import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shooooort</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1>Shooooort</h1>
        </div>
      </main>

      <footer>
      </footer>
    </div>
  )
}
